### ISSUE TITLE
 Carousel card and Adaptive cards is rendered slow and its overlapping when we use in IOS Teams App.

### ISSUE THREAD

**Issue by vishmonne** [microsoft/AdaptiveCards#3125]
**PLATFORM : IOS**

Version: SDK V3 Bot Framework
Deployment : Azure
Language : C#
Adpative card Verison : 1.0
Bot Builder Version : 3.15.3
Platform  Tested: Teams Desktop, Android, Mac Book Teams , Iphone IOS

When run our Chatbot in Teams  using the app id from Azure . 

**Issue Description:** 

We tested our Chabot in all platforms as mentioned above and found the following issues only in Iphone Mobile Teams App.

- Card is rendered very slowly and it gets overlapped as seen in Iphone Screenshot 
![Iphone Screenshot 1](https://user-images.githubusercontent.com/10339913/60445045-12451980-9c3c-11e9-952c-767d46768a7c.jpg)

- •	In Carousel card, the text formatting is not getting wrapped properly though we have given the wrap=true in the code 
![IphoneScreenshot 2](https://user-images.githubusercontent.com/10339913/60445087-2557e980-9c3c-11e9-965f-0655be314bb8.jpg)

- •	Sometimes when the button is clicked, the text border is very large as seen in Iphone Screenshot3 
![Iphone Screenshot 3](https://user-images.githubusercontent.com/10339913/60445122-34d73280-9c3c-11e9-9f2d-f73a5b86e75e.jpg)

In Teams Android ,Desktop and Mac Os i am not facing this issue, it is only happening in IOS Teams App.

It will be really helpful if someone could give a solution for this

**Comment by nesalang** [comment]
Hello @vishmonne 
Thanks for reporting the issue.
I've contacted Teams to check the issue.
Meanwhile, can you share your payloads?

**Comment by vishmonne** [comment]
Hi @nesalang . Thanks for replying back. 

here's the serialized attachment.
[json1 (1).txt](https://github.com/microsoft/AdaptiveCards/files/3348637/json1.1.txt)

Add this in Carousel Layout

**Comment by nesalang** [comment]
@vishmonne 
first & third issue could be Team's issue.
2nd issue i'm looking into it.

**Comment by vishmonne** [comment]
hi @nesalang  , thanks for this update. 

I did a lot of testing in IOS teams app regarding the **first** and **third** issue , i found out that in latest Teams version **1.0.78** and **1.0.77** i am getting this issue, whereas in Teams version **1.0.74** i am not getting this issue. 

So i wanted to know what i can do to solve this one in the latest Teams version and where i can get this issue sorted out.


Regarding the **2nd Issue**, i wanted to know whether we have any ETA for this issue?

Thanks again for helping us in this issue

**Comment by nesalang** [comment]
@vishmonne do you have a contact in Teams to whom you can bring up this issue #1 & #3? 
That will be the best option, and they will appreciate for the valuable feedback.
I'm working on the 2nd issue. can you be more specific on the issue you're facing. There are few layout inconsistencies I observe between iOS and other renders. If you're be specific and point out the most important one, I can focus my efforts in addressing the issue.

**Comment by droidriz** [comment]
@nesalang 
1.wraping of text i.e wrapped correctly in other layouts (Date | Time | TimeZone) next to alternate date/Time in render.
2. The Images size inside column is changing in IOS Render whereas in other render (Android/Desktop) its working as we need i.e layout is being rendered correctly.

**Comment by vishmonne** [comment]
hi @nesalang ,

Main focus is 

-  As u can see in the screenshot , though in the code we have used wrap=true inside the textblock , in the screenshot its not wrapping properly.

-  The image size is not properly getting rendered in IOS whereas the same thing works fine with android and Desktop TEAMS interface
**ANDROID  TEAMS APP**
![Android Screenshot 2](https://user-images.githubusercontent.com/10339913/60653834-72200800-9e68-11e9-9849-b5cbd9e16044.jpg)

**IOS TEAMS APP**
![IphoneScreenshot 2](https://user-images.githubusercontent.com/10339913/60653882-86fc9b80-9e68-11e9-9bb9-a9bdf73da47f.jpg)

U can see how the same code is different in different platforms

**Comment by nesalang** [comment]
@vishmonne 
Thanks for the clarification.
As the issue is being addressed, I suggest making following changes to your payload to get you unblocked.

For 2nd issue, setting the size of Image such as small, medium, large, will resolve the issue.
What happened here is that since the column that contains the image size is auto and the column with text set to stretch, the image has shrunken to adjust for it. If you set the size of image, then the image size will be fixed, so all three images will have the same dimensions.

For 1st issue, you can try using auto & auto or stretch & stretch for those columns that contain TextBlock. You can also use the FactSet, and i think this is the best option.

**Comment by droidriz** [comment]
@nesalang 
Thank you i did try with the image as Large here is the layout issue after that.
![IMG-20190706-WA0001](https://user-images.githubusercontent.com/6308418/60742339-a12e9a80-9f8a-11e9-91da-c1773a29b94f.jpg)

here in the above image the width of the window is small and my card is being only displayed 3/4th also the image is large but when it has 3 lines of text and one image it automatically becomes small its shown in the next image.

![IMG-20190706-WA0000](https://user-images.githubusercontent.com/6308418/60742383-ce7b4880-9f8a-11e9-9fe7-67c5051b46d2.jpg)

Thanks again for helping :)

**Comment by nesalang** [comment]
issue #2 is being tracked by #3159

**Comment by vishmonne** [comment]
hi @nesalang . Thanks for the update on the issue. Would be waiting for a reply on this issue .

**Comment by nesalang** [comment]
@vishmonne ,
#2 is fixed via PR #3195

**Comment by droidriz** [comment]
@nesalang ,
I see the codes have been merged for #2 so what should we do in our code or any nuget package updation  to see the updated adapative cards?

**Comment by vishmonne** [comment]
hi @nesalang , any update on what we should we from our end since the issue #2 is fixed via PR #3195 .
Would be helpful if you could guide us so how we can proceed with this fix?

**Comment by vishmonne** [comment]
hi @nesalang ,  would be helpful if you could help me in proceeding with this fix ?

**Comment by shalinijoshi19** [comment]
hi @vishmonne, #2 has now been fixed and available via [v1.2.1](https://github.com/microsoft/AdaptiveCards/releases/tag/v1.2.1)

**Comment by droidriz** [comment]
@nesalang @shalinijoshi19 we are still facing the issue #2 the images are still being displayed same distorted.

**Comment by shalinijoshi19** [comment]
@nesalang, can you please work with @droidriz to follow up ? Thanks.

**Comment by nesalang** [comment]
@droidriz when you said you've updated adaptive cards to 1.2.1, does that mean Team has updated adaptive cards SDK to 1.2.1? 
Thanks

**Comment by droidriz** [comment]
@nesalang nope i have updated nuget package in the code.
does that means we have to wait till "teams" team in their channel update their adaptive cards to 1.2.1?

**Comment by nesalang** [comment]
@droidriz nuget package is for .net and uwp sdk. for ios, you should use cocoapod. to answer your question, if you send your json payload to teams app to render, then yes teams has to updated their adpative card sdk to 1.2.1. Currently, we are working with them to update to the latest release we made.
thank you.

**Comment by droidriz** [comment]
@nesalang got it, thank you :)

**Comment by droidriz** [comment]
@nesalang  @shalinijoshi19 i know we shouldn't ask for ETA but any vague idea when can we expect the   the "teams" team will update v1.2.1 and release?

**Comment by nesalang** [comment]
@droidriz Teams is actively working on upgrading to v1.2.x, it should happen pretty soon.

**Comment by jjustinms** [comment]
From Teams mobile

1/ Card is rendered very slowly in IOS and it sometimes gets overlapped (screenshot 1)
Agreed the issue is intermittent but we tried with other carousel cards its working fine for those, one primary reason for the rendering slowly is that the son data is too large and there are around 9 cards being rendered at the same time. We suggest using fewer cards as the son data just is some where around 38-39 Kb which needs to be parsed and ui elements be created for the same


2/ In Carousel card, the text formatting is not getting wrapped properly though we have given the wrap=true in the code( screenshot 2)
Fixed in adaptive cards v1.2.1, we have plans to upgrade to that but are right now consolidating known issues for adaptive cards and will soon upgrade to 1.2.1 (time line for 1.2 can be shared by @siduppal)

3/ Sometimes when the button is clicked, the text border sometimes is shown very large ( screenshot 3)
Same as 1 issue is intermittent but acknowledged, RCA looks like since the data is huge reloading table is causing this issue.

4/ Cards misaligned in carousel mode
Fix is being done and will be available in upcoming store builds.

**Comment by shalinijoshi19** [comment]
@nesalang could you take a look at the blurb from @jjustinms see if we still need to keep this bug on us or if we can hand it over to the Teams side for tracking #1 & #2 in Justin's note above. @siduppal FYI (_there isnt work at our end for this bug at the moment but I'll let @nesalang  confirm before handoff_ ) thanks!

**Comment by shalinijoshi19** [comment]
Confirming there is no work at our end here @VikrantSingh01
