### ISSUE TITLE
"value" property of Input.Time and Input.Data not working

### ISSUE THREAD

**Issue by gitmenonsandu** [Microsoft/AdaptiveCards#381]
The value property in Input.Time and Input.Data which sets the initial value of the field is not setting the initial value.
<code>{
"type": "Input.Date",
"id": "onDate",
 "value":"03/21/1996",
"title": "Select due date"
}
</code>
This does not set the initial value

**Comment by anbare** [comment]
Hey @gitmenonsandu, which renderer is this? HTML, UWP, Android, or iOS?

**Comment by dsanvita** [comment]
@gitmenonsandu If you are talking about the html renderer, this pull fixes it: https://github.com/Microsoft/AdaptiveCards/pull/343

**Comment by gitmenonsandu** [comment]
@anbare  HTML renderer

**Comment by dclaux** [comment]
I have fixed both a few days ago.

**Comment by User1m** [comment]
@dclaux having similar issues in the botframework-emulator where default values for Input.Time and Input.Date are not being populated in the UI (aka emulator). Any ideas?

**Comment by dclaux** [comment]
@User1m , it might be that the emulator isn't updated with the latest version of the library, or you didn't update your adaptive cards npm package. Can you check?

**Comment by User1m** [comment]
@dclaux I'm using C# and I manually built the botframework-emulator app from source and made sure the adaptive cards npm package was included, still not working :/

**Comment by dclaux** [comment]
Ah - this issue was opened for the HTML renderer. Not sure about the C# one.

**Comment by zhusongm** [comment]
@User1m I'm preparing a fix for the c# sdk.
