### ISSUE TITLE
[MSTeams][Desktop] "&" character turns in to "&amp;" in Input.ChoiceSet

### ISSUE THREAD

**Issue by dchathu** [microsoft/AdaptiveCards#3894]
# Platform

* MSTeams - Desktop
* .Net Core
* Botframework v4

# Details

In Teams desktop app, If Input.ChoiceSet contains a Choice with "&" Character in Title, that choice is not rendered properly when selected.

![adaptive card bug](https://user-images.githubusercontent.com/8149625/78026285-fa402900-7378-11ea-93a4-3288ace61f2d.PNG)

It renders properly when the drop-down is loaded. Issues is when the choice is selected.

No issues with iOS.

**Comment by Gousia-MSFT** [comment]
@chathudev Thanks for reaching out to us. This is a known issue. We have a bug on this and we are working on it.

**Comment by shalinijoshi19** [comment]
@Gousia-MSFT many thanks for helping out. Would you mind referencing the known issue here (is it on the Teams side?) so we can dup this to that for tracking and close this out ? Thanks!

**Comment by Gousia-MSFT** [comment]
@shalinijoshi19 Yes, this is on the teams side. I have raised a bug for this for the teams team.

**Comment by Wajeed-msft** [comment]
**Updates:** This bug is fixed. We will share updates once this is deployed in public rings.

**Comment by hari8977** [comment]
till i am facing the issue,
I am using adaptive card version 1.3 and 1.5, in both versions i am getting same issue (&" character turns in to "&amp) .

![Screenshot from 2022-09-02 11-36-33](https://user-images.githubusercontent.com/54984531/188069832-67e352a6-3113-4bb4-a199-e06ad73cbbc7.png)

**Comment by ChetanSharma-msft** [comment]
Hello @hari8977 - Sorry for delay in response.
We will check on it from our end and let you know the updates.

**Comment by sayali-MSFT** [comment]
@hari8977 - We are checking the above scenario with adaptive card version with 1.3 and 1.5 as well. It is working fine from our end.
Could you please check it once with updated teams version. 

Microsoft Teams Version 1.5.00.34469 (64-bit)

![adcardcs](https://user-images.githubusercontent.com/93527375/209070852-75e1cd0e-55b7-47de-a9ed-3040873c2f6c.png)

**Comment by icc-simon-korte** [comment]
Hi,
I still face the same issue with AdaptiveCards 1.5 and the latest Teams app.
I'm using the **type-ahead search** functionality. Could it be that you forgot to fix the bug on that end?

Thanks and best regards,
Simon
